### PR TITLE
Remove demo data from mongo init file (#712)

### LINKED ISSUE #712: CalmHub: Init Mongo Script
### Steps to Reproduce:

Init Mongo script is not correct (what is in the integration tests is) for setting up counters. The script was put together to have a few examples.

### Fix

Update the init mongo script to not add any architectures or patterns, but only setup the latest schema.

### PR DESCRIPTION
**Pull request by grahampacker-ms**
Fixes #712

### CODE REVIEW

File: calm-hub/mongo/init-mongo.js [hunk 1]
```diff
@@ -1192,280 +757,5 @@ db.schemas.insertMany([               // Insert initial documents into the schem
...
-        ]
-    },
-    {
-        namespace: "custom",
-        patterns: [
-        ]
-    }
-]);
-
-db.architectures.insertMany([
```
Comment (jpgough-ms) [inline calm-hub/mongo/init-mongo.js:1462]: Does `db.architectures` and `db.patterns` still need to be inserted as empty? Not sure what the code assumptions are.

Comment (grahampacker-ms) [reply calm-hub/mongo/init-mongo.js:1462]: I tested inserts and they worked fine

Comment (grahampacker-ms) [reply calm-hub/mongo/init-mongo.js:1462]: I tested GETs on a new DB and it errors. I'll add the empty inserts to initialise the collection

Comment (grahampacker-ms) [reply calm-hub/mongo/init-mongo.js:1462]: @jpgough-ms fixed, I've put some code protections so an empty collection doesn't cause null pointers. I did try to initialize the collection as empty, but it still cause NPEs

**Review by jpgough-ms — APPROVED** [review]
